on:
  push:
    branches:
      - master

name: Push to Amazon ECR

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v11
      with:
        java-version: 11
    - name: Build with Maven
      run:
        mvn clean package --file pom.xml
